### ISSUE TITLE
Enabling StyleCI

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/seo-bundle#314]
Thought it is still enabled, but it isn't.

**Comment by dbu** [comment]
hm, i see a ton of cmf bundles in styleci but not the seo bundle. and i can't find styleci in https://github.com/symfony-cmf/seo-bundle/settings/installations . any idea?

**Comment by ElectricMaxxx** [comment]
tried to contact styleCI on twitter, forced to write them to their support -> done.

**Comment by GrahamCampbell** [comment]
> forced to write them to their support -> done.

Yeh, sorry about that. It's really hard to give meaningful support on twitter due to the 140 character limit.

**Comment by ElectricMaxxx** [comment]
@GrahamCampbell sorry, forced is maybe a bad word for that. Just wanted to leave a comment for the current state.

**Comment by GrahamCampbell** [comment]
That's fine. I've replied to your email on the support system. :)

**Comment by ElectricMaxxx** [comment]
@GrahamCampbell thanks works now. 

found the bundle among my personal repositories on StyleCI -> enabled it.

**Comment by GrahamCampbell** [comment]
🚀

**Comment by dbu** [comment]
thanks for the help @GrahamCampbell !
