### ISSUE TITLE
1.1.2 not available any longer

### ISSUE THREAD

**Issue by elvis2** [symfony-cmf/seo-bundle#317]
Hello, I went to build an app that is using "symfony-cmf/seo-bundle": "1.1.2", in composer.json, seems that you removed that build from the https://packagist.org/packages/symfony-cmf/seo-bundle ??

Is that a temporary thing? Pretty much all the branches you have on packagist are dev versions, any chance you will have a non-dev and stable version soon?

**Comment by ElectricMaxxx** [comment]
@elvis2 thanks for reporting that issue. I updated the packagist hock,you should see more versions now, right?

**Comment by ElectricMaxxx** [comment]
btw @naderman is there a chance to trigger the update hocks automatically?

**Comment by ElectricMaxxx** [comment]
@dbu i think we should update all our repositories right?

**Comment by elvis2** [comment]
Yep @ElectricMaxxx they are there now. Thank you!

**Comment by dbu** [comment]
> @dbu i think we should update all our repositories right?

hm, did something get lost with the packagist hooks? i would not be aware of needing to update the hook, thought they would automatically do that.
